[phases.setup]
nixPkgs = ['...', 'postgresql', 'nodejs']

[phases.build]
cmds = [
  'bundle install',
  'bundle exec rake assets:precompile'
]

[start]
cmd = 'bundle exec rake db:migrate db:seed && bundle exec puma -C config/puma.rb'
